spring.application.name=FraudAnalysis
spring.mongodb.uri=mongodb://localhost:27017/analysis_db
spring.kafka.bootstrap-servers=localhost:19092
spring.kafka.properties.schema.registry.url=http://localhost:8083
spring.kafka.consumer.group-id=fraud-analysis-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.specific.avro.reader=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
fraud.kafka.topic.request=transfer.analysis.requested
fraud.kafka.topic.decision=fraud.analysis.decision
fraud.kafka.topic.decision-dlt=fraud.analysis.decision.DLT
fraud.analysis.max-transfers-per-second=1
spring.data.mongodb.auto-index-creation=true
server.port=8082
spring.web.error.whitelabel.enabled=false
logging.level.org.apache.kafka=DEBUG
