spring.application.name=FraudAnalysis
spring.mongodb.uri=mongodb://localhost:27017/analysis_db
spring.kafka.bootstrap-servers=localhost:19092
spring.kafka.properties.schema.registry.url=http://localhost:8083
spring.web.error.whitelabel.enabled=false
logging.level.org.apache.kafka=DEBUG
